fixtures:
  symlinks:
    elastalert: "#{source_dir}"
  forge_modules:
    vcsepo:
      repo: "puppetlabs/vcsrepo"
      ref: 1.5.0
    python:
      repo: "stankevich/python"
      ref: 1.18.0
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"

